"""Traductions anglaises du texte des pages. Règle du site : ni tiret long, ni point-virgule, ni deux-points."""
EN = {
'Trouvez le Smart Binder de votre cible dans le catalogue BlackPhage, ou faites-le créer sur mesure.': 'Find the Smart Binder for your target in the BlackPhage catalogue, or have one made for you.',
'BlackPhage': 'BlackPhage',
'Le Smart Binder de votre cible, prêt à commander ou créé pour vous.': 'The Smart Binder for your target, ready to order or made for you.',
'website': 'website',
'Cherchez une cible, ex. TNF': 'Search for a target, e.g. TNF',
'Rechercher une cible': 'Search for a target',
'Smart Binders sur mesure': 'Custom Smart Binders',
'Le Smart Binder de votre cible.': 'The Smart Binder for your target.',
"Choisissez-le dans notre catalogue ou faites-le créer pour vous. Notre équipe vous accompagne de la première question jusqu'à la livraison.": 'Pick it from our catalogue or have it made for you. Our team supports you from your first question to delivery.',
'Voir le catalogue': 'Browse the catalogue',
'Essayez': 'Try',
'TNF': 'TNF', 'PD-L1': 'PD-L1', 'HER2': 'HER2', 'IL-6': 'IL-6',
'Réponse sous': 'Reply within',
'2 jours ouvrés': '2 business days',
'Livraison suivie en': 'Tracked delivery in',
'3 à 7 jours ouvrés': '3 to 7 business days',
'Conseil gratuit avant achat': 'Free advice before you buy',
'Pour commencer': 'Getting started',
"Deux façons d'obtenir votre Smart Binder.": 'Two ways to get your Smart Binder.',
'1': '1', '2': '2',
'Ma cible est dans le catalogue': 'My target is in the catalogue',
'Comparez les formats, voyez le prix tout de suite et ajoutez votre choix à votre commande en quelques clics.': 'Compare sizes, see the price right away and add your choice to your order in a few clicks.',
'Parcourir le catalogue': 'Browse the catalogue',
"Ma cible n'y est pas encore": 'My target is not there yet',
'Décrivez votre besoin en trois petites étapes. Nous revenons vers vous avec une proposition claire, sans engagement.': 'Describe your need in three short steps. We get back to you with a clear proposal and no commitment.',
'Demander une cible': 'Request a target',
'Notre sélection': 'Our picks',
'Une sélection pour démarrer.': 'A selection to get you started.',
'Voir tout le catalogue': 'See the whole catalogue',
'Ils nous font confiance': 'They trust us',
'Ce que disent nos clients.': 'What our customers say.',
'Simple': 'Simple',
'De la recherche à la livraison en trois étapes.': 'From search to delivery in three steps.',
'Cherchez ou décrivez': 'Search or describe',
'Trouvez votre cible dans le catalogue ou décrivez-la en quelques lignes.': 'Find your target in the catalogue or describe it in a few lines.',
'Recevez un devis clair': 'Get a clear quote',
'Nous vérifions votre demande et vous envoyons un devis, sans mauvaise surprise.': 'We check your request and send you a quote with no surprises.',
'Réceptionnez votre commande': 'Receive your order',
'Livraison suivie, et un expert reste disponible si vous avez une question.': 'Tracked delivery, and an expert stays available if you have a question.',
'Une question avant de commander ?': 'A question before you order?',
'Écrivez-nous. Le conseil est gratuit et sans engagement, et nous répondons sous': 'Write to us. Advice is free and carries no commitment, and we reply within',
'.': '.',
"Parler à l'équipe": 'Talk to the team',
'Parcourez le catalogue BlackPhage et trouvez le Smart Binder de votre cible.': 'Browse the BlackPhage catalogue and find the Smart Binder for your target.',
'Catalogue | BlackPhage': 'Catalogue | BlackPhage',
'Cherchez une cible, un nom ou un univers': 'Search for a target, a name or a category',
'Rechercher dans le catalogue': 'Search the catalogue',
'Univers': 'Categories',
'Catalogue': 'Catalogue',
'Trouvez votre Smart Binder.': 'Find your Smart Binder.',
"Tapez le nom d'une cible ou parcourez par univers. Le prix s'affiche tout de suite.": 'Type the name of a target or browse by category. The price shows right away.',
'Effacer': 'Clear',
'Trier par': 'Sort by',
'Pertinence': 'Relevance',
'Prix croissant': 'Price, low to high',
'Nom de A à Z': 'Name, A to Z',
'Bonne nouvelle, nous pouvons le créer pour vous. Poser la question est gratuit.': 'Good news, we can make it for you. Asking is free.',
'Demander cette cible': 'Request this target',
'Vous ne trouvez pas votre cible ?': 'Cannot find your target?',
'Nous la créons pour vous. Vous recevez une proposition claire sous': 'We make it for you. You get a clear proposal within',
', sans engagement.': ', with no commitment.',
'Détails, formats et prix du Smart Binder.': 'Details, sizes and prices of the Smart Binder.',
'Smart Binder | BlackPhage': 'Smart Binder | BlackPhage',
'Chargement du produit': 'Loading the product',
'Vérifiez votre sélection et demandez votre devis.': 'Check your selection and request your quote.',
'Ma commande | BlackPhage': 'My order | BlackPhage',
'Texte de votre demande': 'Text of your request',
'Ma commande': 'My order',
'Votre sélection.': 'Your selection.',
"Vérifiez vos articles puis demandez votre devis. Vous ne payez rien avant d'avoir donné votre accord.": 'Check your items then request your quote. You pay nothing until you have agreed.',
'Votre commande est vide': 'Your order is empty',
'Parcourez le catalogue ou demandez une cible sur mesure.': 'Browse the catalogue or request a custom target.',
'Vider ma commande': 'Empty my order',
'Récapitulatif': 'Summary',
'Articles': 'Items',
'Sous-total': 'Subtotal',
'Livraison': 'Delivery',
'Précisée dans le devis': 'Given in the quote',
'Total estimé': 'Estimated total',
'Votre nom': 'Your name',
'Votre e-mail': 'Your email',
'Votre organisation (facultatif)': 'Your organisation (optional)',
"Un message pour l'équipe (facultatif)": 'A message for the team (optional)',
'Demander mon devis': 'Request my quote',
'Aucun paiement maintenant. Réponse sous': 'No payment now. Reply within',
'Votre demande est prête': 'Your request is ready',
"Votre messagerie va s'ouvrir avec le message déjà rempli. Si rien ne s'ouvre, copiez le texte ci-dessous et envoyez-le à": 'Your email app will open with the message already filled in. If nothing opens, copy the text below and send it to',
'Ouvrir ma messagerie': 'Open my email app',
'Copier le texte': 'Copy the text',
'Votre cible n est pas au catalogue ? Décrivez votre besoin, nous créons votre Smart Binder sur mesure.': 'Your target is not in the catalogue? Describe your need and we make your Smart Binder to order.',
'Demander une cible | BlackPhage': 'Request a target | BlackPhage',
'Un nom, un code ou une description': 'A name, a code or a description',
'Sur mesure': 'Custom',
'Une nouvelle cible ? Nous nous en occupons.': 'A new target? We take care of it.',
'Dites-nous ce que vous cherchez en trois petites étapes. Vous recevez une proposition claire, sans engagement.': 'Tell us what you are looking for in three short steps. You receive a clear proposal with no commitment.',
'Quelle cible vous intéresse ?': 'Which target are you interested in?',
'Un simple nom suffit, nous ferons le reste.': 'A simple name is enough, we will do the rest.',
'Continuer': 'Continue',
'Pour quel usage ?': 'What is it for?',
'Recherche en laboratoire': 'Laboratory research',
"Développement d'un produit": 'Developing a product',
'Je ne sais pas encore': 'I do not know yet',
'Quantité souhaitée': 'Quantity wanted',
'Petite quantité': 'Small quantity',
'Quantité standard': 'Standard quantity',
'Grande quantité': 'Large quantity',
'Échéance': 'Timeline',
'Dès que possible': 'As soon as possible',
'Dans le mois': 'Within the month',
'Pas de date précise': 'No set date',
'Retour': 'Back',
'Autre chose à nous dire (facultatif)': 'Anything else to tell us (optional)',
'Envoyer ma demande': 'Send my request',
'Ce que vous obtenez': 'What you get',
'Une proposition claire sous': 'A clear proposal within',
'Un interlocuteur dédié du début à la fin': 'One dedicated contact from start to finish',
'Aucun engagement avant votre accord': 'No commitment before you agree',
'Un premier échange offert pour cadrer votre besoin': 'A first conversation on us to shape your need',
"Vous préférez regarder d'abord ?": 'Prefer to look around first?',
'BlackPhage met des Smart Binders sur mesure à la disposition des équipes de recherche.': 'BlackPhage makes custom Smart Binders available to research teams.',
'À propos | BlackPhage': 'About | BlackPhage',
'À propos': 'About',
'Des Smart Binders pour avancer plus vite.': 'Smart Binders to move faster.',
'BlackPhage conçoit des molécules sur mesure qui reconnaissent une cible précise. Nous les mettons à votre disposition, simplement.': 'BlackPhage designs custom molecules that recognise a precise target. We make them available to you, simply.',
"Chaque cible est différente. Si la vôtre n'est pas au catalogue, nous la créons pour vous.": 'Every target is different. If yours is not in the catalogue, we make it for you.',
'Clair': 'Clear',
'Des prix visibles, des formats simples et un devis sans mauvaise surprise.': 'Visible prices, simple sizes and a quote with no surprises.',
'À votre écoute': 'Here to listen',
'Une vraie personne répond à vos questions, avant comme après votre commande.': 'A real person answers your questions, before and after your order.',
"Comprendre le vivant. Concevoir l'intervention. Reprendre le contrôle.": 'Understand life. Design the intervention. Take back control.',
'Questions fréquentes': 'Frequently asked questions',
'Vous vous demandez peut-être': 'You may be wondering',
"Qu'est-ce qu'un Smart Binder ?": 'What is a Smart Binder?',
"C'est une molécule conçue pour reconnaître une cible précise. Vous choisissez la cible, nous fournissons le Smart Binder qui lui correspond.": 'It is a molecule designed to recognise one precise target. You choose the target, we supply the matching Smart Binder.',
'Comment passer commande ?': 'How do I place an order?',
'Ajoutez vos produits à votre commande puis demandez votre devis. Nous vous répondons sous': 'Add your products to your order then request your quote. We reply within',
"et le paiement n'a lieu qu'après votre accord.": 'and payment only happens after you agree.',
'Quels sont les délais de livraison ?': 'How long does delivery take?',
'Comptez': 'Allow',
'pour les produits en stock. Pour les produits sur commande, nous confirmons le délai dans votre devis.': 'for products in stock. For made to order products, we confirm the timing in your quote.',
"Ma cible n'est pas dans le catalogue, que faire ?": 'My target is not in the catalogue, what can I do?',
"Faites une demande sur mesure. C'est gratuit et sans engagement, et vous recevez une proposition claire.": 'Make a custom request. It is free with no commitment, and you receive a clear proposal.',
'Puis-je utiliser vos produits pour un traitement ?': 'Can I use your products for a treatment?',
'Non. Nos produits sont réservés à la recherche. Ils ne sont pas destinés à un usage thérapeutique ni au diagnostic.': 'No. Our products are for research only. They are not intended for therapeutic use or diagnosis.',
'Parlons de votre projet.': "Let's talk about your project.",
'Écrivez-nous à': 'Write to us at',
'contact@blackphage.com': 'contact@blackphage.com',
'. Nous répondons sous': '. We reply within',
"Écrire à l'équipe": 'Write to the team',
'Rejoignez l équipe BlackPhage.': 'Join the BlackPhage team.',
'Carrières | BlackPhage': 'Careers | BlackPhage',
'Candidature Relation client': 'Application Customer relations',
'Candidature Ingénieur·e protéines': 'Application Protein engineer',
'Candidature Développeur·se web': 'Application Web developer',
'Candidature Développement commercial': 'Application Business development',
'Carrières': 'Careers',
"Rejoignez l'équipe BlackPhage.": 'Join the BlackPhage team.',
"Nous construisons une nouvelle façon d'obtenir des Smart Binders. Si vous aimez les défis concrets, parlons-en.": 'We are building a new way to get Smart Binders. If you like concrete challenges, let us talk.',
'Une équipe à taille humaine': 'A human sized team',
'Des décisions rapides et des idées qui comptent.': 'Quick decisions and ideas that count.',
'Un impact concret': 'A real impact',
'Votre travail aide directement des équipes de recherche à avancer.': 'Your work directly helps research teams move forward.',
'Un cadre qui vous fait grandir': 'A setting where you grow',
'Vous apprenez chaque semaine, avec des collègues qui partagent.': 'You learn every week, alongside colleagues who share.',
'Postes ouverts': 'Open positions',
'Nous recrutons.': 'We are hiring.',
'Boutique': 'Shop',
'Temps plein': 'Full time',
'Responsable relation client': 'Customer relations manager',
"Accompagner nos clients de leur première question jusqu'à la livraison.": 'Support our customers from their first question to delivery.',
'Postuler': 'Apply',
'Laboratoire': 'Laboratory',
'Ingénieur·e protéines': 'Protein engineer',
'Préparer, contrôler et expédier nos Smart Binders avec soin.': 'Prepare, check and ship our Smart Binders with care.',
'Équipe digitale': 'Digital team',
'Développeur·se web': 'Web developer',
'Faire évoluer notre boutique pour que commander soit toujours plus simple.': 'Evolve our shop so that ordering gets ever simpler.',
'Ventes': 'Sales',
'Chargé·e de développement commercial': 'Business development executive',
'Aller à la rencontre des équipes de recherche et construire des relations durables.': 'Meet research teams and build lasting relationships.',
'Aucun poste ne vous correspond ?': 'No role fits you?',
'Écrivez-nous quand même. Dites-nous ce que vous savez faire et ce qui vous donne envie.': 'Write to us anyway. Tell us what you can do and what excites you.',
'Candidature spontanée': 'Open application',
}
